### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 39GodMissing** [InvestMaestri/FacialCompareAI#1]
Do you have any recommended datasets that match the operation of your code？Thankyou!

**Comment by 39GodMissing** [comment]
Could you provide a dataset？Thankyou！

**Comment by InvestMaestri** [comment]
> Do you have any recommended datasets that match the operation of your code？Thankyou!

The code automatically generates combinations, so any dataset of faces will do. Just make sure that they are labeled
"firstname lastname_i" ie. "Snoop Dogg_1" or "Shin Min Ah_9" so the code will know to label the image pairs as the same face, meaning that the words before the underscore are the same, otherwise it will label them different faces.



> Could you provide a dataset？Thankyou！
I cannot provide a dataset for two reasons, the first is because of the image rights, and the second is because of the size it would come out as. 
One thing you can do is create your dataset on the fly. I did that using bing_image_downloader library to download a number of images from celebrities:

```
def main(celebrity):
    celebrities = [celebrity]  # Add more celebrity names as needed
    limit_per_celebrity = 25  # Number of images to download per celebrity
    output_folder = "celebrity_images"  # Folder to save the images
```

Best of luck and let me know what you find!

**Comment by 39GodMissing** [comment]
Thank you very much for your reply, and I'm also sorry for not replying to you for so long.

May I ask you some other questions?

Why am I running 2_ CompareGUI_ MTCNN. py and 2_ CompareGUI.py shows that faces cannot be recognized. Did these two py files run simultaneously through a single command, or what does it mean? 3_ What is the purpose of the empty file CompareGUI - Database or LiveFeed. py?

Sorry to bother you, could you please reply to me if you have free time?

**Comment by 39GodMissing** [comment]
Will the file 'weights. best. hdf5' be automatically updated? Because my training set has changed many times

**Comment by 39GodMissing** [comment]
I already understand what's going on, thank you very much！
